# Generated by Django 2.1.2 on 2018-10-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('email', models.EmailField(max_length=128, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('description', models.TextField()),
                ('likes', models.ManyToManyField(to='pintapp.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pintapp.MyUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pintapp.Photo'),
        ),
    ]
